name: Deploy to Deta
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: "fembed-api" 
          deta-project: "fembed-api" #Optional: Deta project name https://docs.deta.sh/docs/cli/commands/#deta-clone
          # deta-project-dir: "other-dir" #Optional: directory to be deployed on Deta. Default is the root "."
